"""add_arrived_status_receptionist_role_waitlist_table

Revision ID: 04a0440c36eb
Revises: 001_initial
Create Date: 2026-04-25 04:59:36.498460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a0440c36eb'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new enum values to existing PostgreSQL enum types
    op.execute("ALTER TYPE appointmentstatus ADD VALUE IF NOT EXISTS 'ARRIVED' AFTER 'CONFIRMED'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'RECEPTIONIST' AFTER 'DOCTOR'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'doctor_id', name='uq_waitlist_patient_doctor')
    )
    op.create_index(op.f('ix_waitlist_created_at'), 'waitlist', ['created_at'], unique=False)
    op.create_index(op.f('ix_waitlist_doctor_id'), 'waitlist', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_waitlist_id'), 'waitlist', ['id'], unique=False)
    op.create_index(op.f('ix_waitlist_patient_id'), 'waitlist', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_patient_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_doctor_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_created_at'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
