"""implement_task_workflow_gaps

Revision ID: 7e0a9223104c
Revises: 06c1234abcde
Create Date: 2026-04-28 21:59:23.287469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e0a9223104c'
down_revision: Union[str, None] = '06c1234abcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first using raw SQL for idempotency
    op.execute("DO $$ BEGIN CREATE TYPE refundstatus AS ENUM ('NONE','PENDING','COMPLETED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE claimstatus AS ENUM ('PENDING','SUBMITTED','APPROVED','DENIED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE labresultstatus AS ENUM ('ORDERED','COMPLETED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$")
    # Add RESCHEDULE_REQUESTED to existing appointmentstatus enum
    op.execute("ALTER TYPE appointmentstatus ADD VALUE IF NOT EXISTS 'RESCHEDULE_REQUESTED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_coverages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('group_number', sa.String(length=100), nullable=True),
    sa.Column('coverage_start', sa.Date(), nullable=False),
    sa.Column('coverage_end', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('copay_percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Percentage the patient pays, e.g. 20 means insurer covers 80%'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_coverages_id'), 'insurance_coverages', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_coverages_patient_id'), 'insurance_coverages', ['patient_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_notes', sa.Text(), nullable=True),
    sa.Column('vitals_json', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='e.g. {blood_pressure, heart_rate, temperature, weight, height}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_encounters_doctor_id'), 'encounters', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_encounters_id'), 'encounters', ['id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('insurance_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('coverage_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('covered_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('patient_responsibility', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUBMITTED', 'APPROVED', 'DENIED', name='claimstatus', create_type=False), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coverage_id'], ['insurance_coverages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', name='uq_claim_appointment')
    )
    op.create_index(op.f('ix_insurance_claims_appointment_id'), 'insurance_claims', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_coverage_id'), 'insurance_claims', ['coverage_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_id'), 'insurance_claims', ['id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=False),
    sa.Column('result_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('reference_range', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('ORDERED', 'COMPLETED', name='labresultstatus', create_type=False), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_encounter_id'), 'lab_results', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.Text(), nullable=False),
    sa.Column('dosage', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_encounter_id'), 'prescriptions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.add_column('appointments', sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('appointments', sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('appointments', sa.Column('penalty_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('appointments', sa.Column('refund_status', postgresql.ENUM('NONE', 'PENDING', 'COMPLETED', name='refundstatus', create_type=False), nullable=False, server_default='NONE'))
    op.add_column('appointments', sa.Column('payment_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Server-side slot hold expiry for VNPay payment window'))
    op.add_column('appointments', sa.Column('proposed_new_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('reschedule_requested_by', sa.String(length=10), nullable=True, comment="'patient' or 'doctor'"))
    op.add_column('appointments', sa.Column('status_before_reschedule_request', sa.String(length=30), nullable=True, comment='Status to revert to if reschedule is declined'))
    op.add_column('appointments', sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('appointments', sa.Column('reminder_2h_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('appointments', sa.Column('follow_up_of', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('follow_up_recommended', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('appointments', sa.Column('follow_up_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'appointments', ['follow_up_of'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'follow_up_date')
    op.drop_column('appointments', 'follow_up_recommended')
    op.drop_column('appointments', 'follow_up_of')
    op.drop_column('appointments', 'reminder_2h_sent')
    op.drop_column('appointments', 'reminder_24h_sent')
    op.drop_column('appointments', 'status_before_reschedule_request')
    op.drop_column('appointments', 'reschedule_requested_by')
    op.drop_column('appointments', 'proposed_new_time')
    op.drop_column('appointments', 'payment_expires_at')
    op.drop_column('appointments', 'refund_status')
    op.drop_column('appointments', 'penalty_amount')
    op.drop_column('appointments', 'refund_amount')
    op.drop_column('appointments', 'deposit_amount')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_encounter_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_encounter_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_insurance_claims_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_coverage_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_appointment_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_doctor_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_insurance_coverages_patient_id'), table_name='insurance_coverages')
    op.drop_index(op.f('ix_insurance_coverages_id'), table_name='insurance_coverages')
    op.drop_table('insurance_coverages')
    # ### end Alembic commands ###
